/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include <vector>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1086456_30.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1086456_9[] = { "closed_eye", "open_eye", "yawning" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1086456_29_axes[] = { 0 };
const uint32_t ei_dsp_config_1086456_29_axes_size = 1;
ei_dsp_config_image_t ei_dsp_config_1086456_29 = {
    29, // uint32_t blockId
    1, // int implementationVersion
    1, // int length of axes
    NULL, // named axes
    0, // size of the named axes array
    "RGB" // select channels
};

const uint8_t ei_dsp_blocks_1086456_9_size = 1;
ei_model_dsp_t ei_dsp_blocks_1086456_9[ei_dsp_blocks_1086456_9_size] = {
    { // DSP block 29
        29,
        519168, // output size
        &extract_image_features, // DSP function pointer
        (void*)&ei_dsp_config_1086456_29, // pointer to config struct
        ei_dsp_config_1086456_29_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1086456_29_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_1086456_30 = {
    .implementation_version = 1,
    .model = tflite_learn_1086456_30,
    .model_size = tflite_learn_1086456_30_len,
    .arena_size = tflite_learn_1086456_30_arena_size
};

const uint8_t ei_output_tensors_indices_1086456_30[1] = { 0 };
const uint8_t ei_output_tensors_size_1086456_30 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1086456_30 = {
    .implementation_version = 1,
    .block_id = 30,
    .output_tensors_indices = ei_output_tensors_indices_1086456_30,
    .output_tensors_size = ei_output_tensors_size_1086456_30,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_1086456_30,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1086456_9_size = 1;
const uint32_t ei_learning_block_1086456_30_inputs[1] = { 29 };
const uint8_t ei_learning_block_1086456_30_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1086456_9[ei_learning_blocks_1086456_9_size] = {
    {
        30,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1086456_30,
        EI_CLASSIFIER_IMAGE_SCALING_0_255,
        ei_learning_block_1086456_30_inputs,
        ei_learning_block_1086456_30_inputs_size,
    },
};

const ei_object_detection_nms_config_t ei_object_detection_nms_1086456_30 = {
    0.0f, /* NMS confidence threshold */
    0.2f  /* NMS IOU threshold */
};
ei_fill_result_object_detection_f32_config_t ei_fill_result_object_detection_f32_config_1086456_30 = {
    .threshold = 0.2,
    .version = 0,
    .object_detection_count = 10,
    .output_features_count = 28392,
    .nms_config = ei_object_detection_nms_1086456_30
};

const size_t ei_postprocessing_blocks_1086456_9_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1086456_9[ei_postprocessing_blocks_1086456_9_size] = {
    {
        .block_id = 30,
        .type = EI_CLASSIFIER_MODE_OBJECT_DETECTION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_yolox_f32,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_object_detection_f32_config_1086456_30,
        .input_block_id = 30
    },
};

const uint8_t freeform_outputs_1086456_9_size = 0;

uint32_t *freeform_outputs_1086456_9 = nullptr;

const ei_impulse_t impulse_1086456_9 = {
    .project_id = 1086456,
    .project_owner = "Thinh1210",
    .project_name = "Test0",
    .impulse_id = 9,
    .impulse_name = "Impulse #9",
    .deploy_version = 12,

    .nn_input_frame_size = 519168,
    .raw_sample_count = 173056,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 173056 * 1,
    .input_width = 416,
    .input_height = 416,
    .input_frames = 1,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_1086456_9_size,
    .dsp_blocks = ei_dsp_blocks_1086456_9,

    .learning_blocks_size = ei_learning_blocks_1086456_9_size,
    .learning_blocks = ei_learning_blocks_1086456_9,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1086456_9_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1086456_9,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_CAMERA,
    .fusion_string = "image",
    .slice_size = (173056/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_1086456_9,
    .results_type = EI_CLASSIFIER_TYPE_OBJECT_DETECTION,
    .freeform_outputs_size = freeform_outputs_1086456_9_size,
    .freeform_outputs = freeform_outputs_1086456_9
};

ei_impulse_handle_t impulse_handle_1086456_9 = ei_impulse_handle_t( &impulse_1086456_9 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1086456_9;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1086456_9;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1086456_9_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1086456_9;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
